# Generated by Django 2.0.5 on 2018-05-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0003_codeserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeserver',
            name='title',
            field=models.CharField(default=2, max_length=64, unique=True, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codeserver',
            name='person_token',
            field=models.CharField(max_length=64, unique=True, verbose_name='PERSON_TOKEN'),
        ),
        migrations.AlterField(
            model_name='codeserver',
            name='url',
            field=models.URLField(max_length=64, verbose_name='gitLab服务器地址'),
        ),
    ]
