# Generated by Django 2.0.5 on 2018-05-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0004_auto_20180503_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeserver',
            name='myuser',
        ),
        migrations.DeleteModel(
            name='CodeServer',
        ),
    ]
