# Generated by Django 2.0.5 on 2018-05-03 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0005_auto_20180503_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='标题')),
                ('url', models.URLField(max_length=64, verbose_name='gitLab服务器地址')),
                ('person_token', models.CharField(max_length=64, unique=True, verbose_name='PERSON_TOKEN')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
