# Generated by Django 2.0.5 on 2018-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0007_buildtools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildtools',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
