# Generated by Django 2.0.5 on 2018-05-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0009_auto_20180508_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildProjectAndBranch',
        ),
    ]
