# Generated by Django 2.0.5 on 2018-05-08 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0010_delete_buildprojectandbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildProjectAndBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_repo', models.URLField(unique=True)),
                ('branch', models.CharField(max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('buildtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cicd.BuildTools')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
