# Generated by Django 2.0.5 on 2018-05-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0012_buildprojectandbranch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildprojectandbranch',
            name='name',
        ),
    ]
