# Generated by Django 2.0.5 on 2018-05-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0013_remove_buildprojectandbranch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildprojectandbranch',
            name='git_repo',
            field=models.URLField(),
        ),
    ]
