# Generated by Django 2.0.5 on 2018-05-15 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0014_auto_20180514_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildtools',
            name='email',
        ),
    ]
