# Generated by Django 2.0.5 on 2018-05-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicd', '0015_remove_buildtools_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildtools',
            name='artifact',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
